# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d9f3af2da34acb0b562db59a28331d899d0a2de1d740d9933324e7857c38a44ccdf96b54241518d0431a11a8ec3018958e0119a4025072677644a8113fcc328

test:
  secret_key_base: 8afdf921fee6ebba39d1d29d5cc8f267d2450a9aa3578bd365aeb7417ac2fb02e4b211df74f769289aa4e91d525ebc013e760b6427489f7467812522908fd875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
